### ISSUE TITLE
Story: UI Flow of provider frontend

### ISSUE THREAD

**Issue by lokmeinmatz** [docweirdo/verplant#7]
A provider wants to see it's booking processes

* in a calendar view (highlighted by selected process) to resolve collisions #5 
* in a card view specific to this booking (reuse cards from user-frontend)

Toggle to switch between those two views?

The booking processes are shown in a list #6 
* side-by-side (left: list, right: view specified above)
* full: tap on entry navigates to view specivied above

### TODOs
- [ ] should the calendar view allow to switch booking when a "foreign" event was clicked?
- [ ] color coding of calendar and list (prefeered: coding of appointment-list: reuse status colors)
- [ ] how to toggle between views
- [ ] explicit notification when booking process is switched (prevent accidential appointment for wrong user)
